name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Repackage AWS CLI v2 for Darwin
        run: ./repackage-awscli darwin
      - name: Repackage AWS CLI v2 for Linux
        run: ./repackage-awscli linux
