name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repackage AWS CLI v2 for Linux
        run: ./repackage-awscli linux
      - name: Repackage AWS CLI v2 for Darwin
        run: ./repackage-awscli darwin
