name: release

on:
  push:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "repackage/*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
